name: Conventional Commits

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Conventional Commits
        uses: webiny/action-conventional-commits@v1.3.0
      
      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v4
        with:
          server_address: ${{ secrets.MAIL_SERVER }}
          server_port: ${{ secrets.MAIL_PORT }}
          username: ${{ secrets.MAIL_USERNAME}}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Conventional Commits check failed
          to: ${{ secrets.EMAIL_DESTINATION }}
          from: GitHub Workflow
          body: The Conventional Commits check has failed for PR ${{ github.event.pull_request.html_url }}
      
      - name: Close the PR If It Fails
        if: failure()
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: Auto-closing pull request for not adhering to conventional commits
          delete-branch: true